language: shell
os: linux
dist: trusty

script:
  - export FILE_NAME=openHAB-$TRAVIS_BRANCH-syno-noarch-0.001.spk
  - echo $FILE_NAME
  - chmod a+x scripts/*
  - tar cf $FILE_NAME * --exclude=*.md --exclude=.travis.*  --owner=0 --group=0 --numeric-owner

deploy:
  cleanup: true
  provider: releases
  token:
    secure: "$GITHUB_TOKEN"
  file:
    - $FILE_NAME
  on:
    tags: true

notifications:
  email:
    - c-n-i@web.de
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ad63d38810d8674398c4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
