language: shell
os: linux
dist: trusty

script:
  - export FILE_NAME=openHAB-$TRAVIS_BRANCH-syno-noarch-0.001.spk
  - echo $FILE_NAME
  - chmod a+x scripts/*
  - tar cf $FILE_NAME * --exclude=*.md --exclude=.travis.*  --owner=0 --group=0 --numeric-owner

deploy:
  cleanup: true
  provider: releases
  token:
    secure: $GITHUB_TOKEN
  file:
    - $FILE_NAME
  on:
    tags: true

notifications:
  email:
    - c-n-i@web.de
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ad63d38810d8674398c4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

secure: "aoHb/LMCDQNUV+WUZmYrldu9NkT6MocYqfu+oLkNYGswQjraagAGkwH26U83WRk87wH4zJCfTqPwPBxXA/BWBCilf/UnK9vYDPuRU4Zz89cwnLTfS+KJ/yakOXTKS08Ak8+srqGBzh+T12iAJ8/Sm6CvxLvPr8YdeSQ7sF5UzkOT9few5re4iR+noBQCG8ShVX272asEJglUGQoU+hNzbbmETqOqBpbOJY+I+uJERbBUHgBZJdgMLeJCzrhfPfS/lJUuYe429rToL0k1jT8reDFFcUrLenRN+whyIniIl7NnBzOOOrKXy1QG2XY1Jt4rT7kXuZ/Zhs+QPnbxdsVebeeYCWuU5oR8zp3FNjZ7w3pjiG0Z8gAlVtDr32q5AxMxlf0ualfp71Q1T9T2cEMajNILZm6G8HmhdIGXos8JhQMEZclvOhJ8xeOxRMHEBV/5/QoCJ/LA4fKagQKJGzYLK+QGiIJ0PoDgGwHii7F5Cibq5dRHooJKU3dDgr6rNXrLrVpQdTbwBmarTOl4w4CMCm55/VDPnA/8Wbi52dd12sccTAJru7JIGDm59xgN+f79q1mTYKcC/v3kaY8tm+ntYi5jIoDgSoxWHznK/DdUHvMrsAuFb3bEfVYkrgHr2A12L3Mk+m9JsClo0lDc4QXynlExqOjdxgdkmEoevbPNeeA="
